import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        include: [
            'tests/unit.spec.ts',
            'tests/chrome-store-publisher.spec.ts',
            'tests/storage.spec.ts',
            'tests/content-lifecycle.spec.ts',
            'tests/site-access.spec.ts',
        ],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'json-summary'],
            include: [
                'src/keyboard-layout.ts',
                'src/prompt-builder.ts',
                'src/markdown.ts',
                'src/mistral-client.ts',
                'src/site-profiles.ts',
                'src/site-access.ts',
                'src/spellcheck.ts',
                'src/request-cache.ts',
                'src/ai-cache.ts',
                'src/appearance-style.ts',
                'src/history-store.ts',
                'src/usage-stats.ts',
                'src/settings-store.ts',
                'src/request-lifecycle.ts',
                'src/content-stream-renderer.ts',
                'src/result-display-mode.ts',
                'src/privacy.ts',
                'src/request-validation.ts',
                'src/adaptive-model-store.ts',
                'src/settings-migrations.ts',
                'src/storage-queue.ts',
                'src/budget.ts',
                'src/budget-reservations.ts',
                'src/theme-customization.ts',
                'src/idb.ts',
                'src/content-language-picker.ts',
                'src/dom-rendering.ts',
                'src/text-stats.ts',
                'src/content-dialog-accessibility.ts',
            ],
            thresholds: { lines: 68, functions: 58, statements: 62, branches: 53 },
        },
    },
});
