import { defineConfig } from 'vitest/config';

export default defineConfig({
    define: {
        __LEXISYNC_GOOGLE_DRIVE_FIREFOX_CLIENT_ID__: JSON.stringify('firefox-test-client-id'),
    },
    test: {
        include: [
            'tests/ai-security.spec.ts',
            'tests/unit.spec.ts',
            'tests/chrome-store-publisher.spec.ts',
            'tests/storage.spec.ts',
            'tests/content-lifecycle.spec.ts',
            'tests/site-access.spec.ts',
            'tests/crypto-backup.spec.ts',
            'tests/google-drive-auth.spec.ts',
            'tests/ai-quality.spec.ts',
            'tests/ai-resilience.spec.ts',
        ],
        coverage: {
            provider: 'v8',
            reporter: ['text', 'json-summary'],
            include: [
                'src/ai-sanity-check.ts',
                'src/cloudflare-client.ts',
                'src/cloudflare-provider.ts',
                'src/ai-client.ts',
                'src/ai-provider-types.ts',
                'src/provider-health.ts',
                'src/keyboard-layout.ts',
                'src/prompt-builder.ts',
                'src/markdown.ts',
                'src/mistral-client.ts',
                'src/site-profiles.ts',
                'src/site-access.ts',
                'src/spellcheck.ts',
                'src/request-cache.ts',
                'src/ai-cache.ts',
                'src/appearance-style.ts',
                'src/runtime-settings-cache.ts',
                'src/site-runtime-access.ts',
                'src/history-store.ts',
                'src/usage-stats.ts',
                'src/settings-store.ts',
                'src/request-lifecycle.ts',
                'src/content-stream-renderer.ts',
                'src/result-display-mode.ts',
                'src/privacy.ts',
                'src/request-validation.ts',
                'src/adaptive-model-store.ts',
                'src/settings-migrations.ts',
                'src/settings-transfer.ts',
                'src/storage-queue.ts',
                'src/budget.ts',
                'src/budget-reservations.ts',
                'src/theme-customization.ts',
                'src/idb.ts',
                'src/content-language-picker.ts',
                'src/dom-rendering.ts',
                'src/text-stats.ts',
                'src/content-dialog-accessibility.ts',
                'src/diagnostics.ts',
                'src/popup-position.ts',
                'src/crypto-backup.ts',
                'src/google-drive-sync.ts',
                'src/google-drive-auth.ts',
                'src/provider-availability.ts',
                'src/sse-parser.ts',
            ],
            thresholds: { lines: 68, functions: 58, statements: 62, branches: 53 },
        },
    },
});
