const ALLOWED_INPUT_TYPES = new Set(['text', 'search']);

const SENSITIVE_AUTOCOMPLETE_TOKENS = new Set([
    'name',
    'honorific-prefix',
    'given-name',
    'additional-name',
    'family-name',
    'honorific-suffix',
    'nickname',
    'username',
    'new-password',
    'current-password',
    'one-time-code',
    'organization-title',
    'organization',
    'street-address',
    'address-line1',
    'address-line2',
    'address-line3',
    'address-level1',
    'address-level2',
    'address-level3',
    'address-level4',
    'country',
    'country-name',
    'postal-code',
    'cc-name',
    'cc-given-name',
    'cc-additional-name',
    'cc-family-name',
    'cc-number',
    'cc-exp',
    'cc-exp-month',
    'cc-exp-year',
    'cc-csc',
    'cc-type',
    'transaction-currency',
    'transaction-amount',
    'bday',
    'bday-day',
    'bday-month',
    'bday-year',
    'sex',
    'url',
    'photo',
    'tel',
    'tel-country-code',
    'tel-national',
    'tel-area-code',
    'tel-local',
    'tel-local-prefix',
    'tel-local-suffix',
    'tel-extension',
    'email',
    'impp',
]);

export function shouldAutoProofreadField(inputType: string | null, autocomplete: string): boolean {
    if (inputType !== null && !ALLOWED_INPUT_TYPES.has(inputType.toLowerCase())) return false;
    return !autocomplete
        .toLowerCase()
        .split(/\s+/)
        .some((token) => SENSITIVE_AUTOCOMPLETE_TOKENS.has(token));
}
